In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Import dataset for initial inspection

In [2]:
vaccines = pd.read_csv("../data/raw/COV_VAC_UPTAKE_2021_2023.csv")

### Initial inspection
- First/last rows
- Shape of dataset
- Column names and dtypes
- Describe

In [3]:
vaccines.head()

,COUNTRY,COVID_VACCINE_ADM_TOT_A1D,COVID_VACCINE_ADM_TOT_BOOST,COVID_VACCINE_ADM_TOT_CPS,COVID_VACCINE_ADM_TOT_DOSES,COVID_VACCINE_ADM_TOT_DOSES_PER100,COVID_VACCINE_COV_TOT_A1D,COVID_VACCINE_COV_TOT_BOOST,COVID_VACCINE_COV_TOT_CPS,COVID_VACCINE_DATE_INTRO_FIRST,COVID_VACCINE_DATE_REPORT_TOT_LAST,DATE
0,BTN,187866.0,NaN,NaN,187866.0,24.0,24.0,NaN,NaN,2021-03-27,2022-10-30,2021-03-28
1,BTN,480836.0,NaN,NaN,480836.0,62.0,62.0,NaN,NaN,2021-03-27,2022-10-30,2021-04-25
2,BTN,483092.0,NaN,NaN,483092.0,63.0,63.0,NaN,NaN,2021-03-27,2022-10-30,2021-05-30
3,BTN,484797.0,NaN,490.0,485619.0,63.0,63.0,NaN,NaN,2021-03-27,2022-10-30,2021-06-27
4,BTN,530103.0,NaN,470465.0,1000568.0,130.0,69.0,NaN,61.0,2021-03-27,2022-10-30,2021-07-25

In [4]:
vaccines.tail()

,COUNTRY,COVID_VACCINE_ADM_TOT_A1D,COVID_VACCINE_ADM_TOT_BOOST,COVID_VACCINE_ADM_TOT_CPS,COVID_VACCINE_ADM_TOT_DOSES,COVID_VACCINE_ADM_TOT_DOSES_PER100,COVID_VACCINE_COV_TOT_A1D,COVID_VACCINE_COV_TOT_BOOST,COVID_VACCINE_COV_TOT_CPS,COVID_VACCINE_DATE_INTRO_FIRST,COVID_VACCINE_DATE_REPORT_TOT_LAST,DATE
7603,TWN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-12-31
7604,VNM,90497674.0,57975220.0,85961564.0,266492149.0,274.0,93.0,60.0,88.0,2021-03-08,2023-06-30,2023-12-31
7605,VUT,176624.0,16556.0,162250.0,355430.0,116.0,58.0,5.0,53.0,2021-06-02,2023-02-20,2023-12-31
7606,WLF,7150.0,3350.0,6803.0,17303.0,154.0,64.0,30.0,60.0,2021-03-19,2023-01-23,2023-12-31
7607,WSM,191403.0,82268.0,177954.0,453130.0,228.0,96.0,41.0,90.0,2021-04-18,2023-02-24,2023-12-31

In [5]:
vaccines.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7608 entries, 0 to 7607
Data columns (total 12 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   COUNTRY                             7608 non-null   object
 1   COVID_VACCINE_ADM_TOT_A1D           7329 non-null   float64
 2   COVID_VACCINE_ADM_TOT_BOOST         4830 non-null   float64
 3   COVID_VACCINE_ADM_TOT_CPS           7101 non-null   float64
 4   COVID_VACCINE_ADM_TOT_DOSES         7426 non-null   float64
 5   COVID_VACCINE_ADM_TOT_DOSES_PER100  7199 non-null   float64
 6   COVID_VACCINE_COV_TOT_A1D           7112 non-null   float64
 7   COVID_VACCINE_COV_TOT_BOOST         4403 non-null   float64
 8   COVID_VACCINE_COV_TOT_CPS           6803 non-null   float64
 9   COVID_VACCINE_DATE_INTRO_FIRST      6807 non-null   object
 10  COVID_VACCINE_DATE_REPORT_TOT_LAST  7375 non-null   object
 11  DATE                                7608 non-null   object
dtypes: float64(8), object(4)
memory usage: 713.4+ KB

In [6]:
vaccines.columns = [x.title() for x in vaccines.columns]

In [7]:
vaccines.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7608 entries, 0 to 7607
Data columns (total 12 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Country                             7608 non-null   object
 1   Covid_Vaccine_Adm_Tot_A1D           7329 non-null   float64
 2   Covid_Vaccine_Adm_Tot_Boost         4830 non-null   float64
 3   Covid_Vaccine_Adm_Tot_Cps           7101 non-null   float64
 4   Covid_Vaccine_Adm_Tot_Doses         7426 non-null   float64
 5   Covid_Vaccine_Adm_Tot_Doses_Per100  7199 non-null   float64
 6   Covid_Vaccine_Cov_Tot_A1D           7112 non-null   float64
 7   Covid_Vaccine_Cov_Tot_Boost         4403 non-null   float64
 8   Covid_Vaccine_Cov_Tot_Cps           6803 non-null   float64
 9   Covid_Vaccine_Date_Intro_First      6807 non-null   object
 10  Covid_Vaccine_Date_Report_Tot_Last  7375 non-null   object
 11  Date                                7608 non-null   object
dtypes: float64(8), object(4)
memory usage: 713.4+ KB

In [8]:
vaccines.describe().T

,count,mean,std,min,25%,50%,75%,max
Covid_Vaccine_Adm_Tot_A1D,7329.0,2.111683e+07,1.049170e+08,11.0,191660.0,1951054.0,7978710.0,1.318027e+09
Covid_Vaccine_Adm_Tot_Boost,4830.0,1.092436e+07,5.811423e+07,1.0,43079.0,575651.0,4364627.5,8.340601e+08
Covid_Vaccine_Adm_Tot_Cps,7101.0,1.900064e+07,9.849577e+07,2.0,163032.0,1427883.0,6887907.0,1.284480e+09
Covid_Vaccine_Adm_Tot_Doses,7426.0,4.757045e+07,2.480843e+08,20.0,355430.0,3026728.0,17074861.0,3.516881e+09
Covid_Vaccine_Adm_Tot_Doses_Per100,7199.0,1.179469e+02,8.402130e+01,1.0,44.0,110.0,182.0,4.700000e+02
Covid_Vaccine_Cov_Tot_A1D,7112.0,5.224297e+01,2.841871e+01,1.0,28.0,57.0,77.0,1.000000e+02
Covid_Vaccine_Cov_Tot_Boost,4403.0,3.009970e+01,2.295098e+01,1.0,8.0,28.0,51.0,8.300000e+01
Covid_Vaccine_Cov_Tot_Cps,6803.0,4.845024e+01,2.771003e+01,1.0,25.0,51.0,72.0,1.000000e+02

## Nulls and duplicates

### Null values

In [9]:
vaccines.isna().sum()/len(vaccines) * 100

Country                                0.000000
Covid_Vaccine_Adm_Tot_A1D              3.667192
Covid_Vaccine_Adm_Tot_Boost           36.514196
Covid_Vaccine_Adm_Tot_Cps              6.664038
Covid_Vaccine_Adm_Tot_Doses            2.392219
Covid_Vaccine_Adm_Tot_Doses_Per100     5.375920
Covid_Vaccine_Cov_Tot_A1D              6.519453
Covid_Vaccine_Cov_Tot_Boost           42.126709
Covid_Vaccine_Cov_Tot_Cps             10.580967
Covid_Vaccine_Date_Intro_First        10.528391
Covid_Vaccine_Date_Report_Tot_Last     3.062566
Date                                   0.000000
dtype: float64

In [10]:
vaccines = vaccines.sort_values(['Country', 'Date'])

In [11]:
cols_to_ffill = [i for i in vaccines.columns if i not in ['Country', 'Date']]
vaccines[cols_to_ffill] = (vaccines.groupby('Country')[cols_to_ffill].ffill())

In [12]:
vaccines.isna().sum()/len(vaccines) * 100

Country                                0.000000
Covid_Vaccine_Adm_Tot_A1D              3.667192
Covid_Vaccine_Adm_Tot_Boost           36.514196
Covid_Vaccine_Adm_Tot_Cps              6.664038
Covid_Vaccine_Adm_Tot_Doses            2.392219
Covid_Vaccine_Adm_Tot_Doses_Per100     5.375920
Covid_Vaccine_Cov_Tot_A1D              6.519453
Covid_Vaccine_Cov_Tot_Boost           42.126709
Covid_Vaccine_Cov_Tot_Cps             10.580967
Covid_Vaccine_Date_Intro_First        10.528391
Covid_Vaccine_Date_Report_Tot_Last     3.062566
Date                                   0.000000
dtype: float64

After applying forward fill to the selected columns, the proportion of missing values remained unchanged. This suggests that the missing data is not due to reporting gaps, but rather because these values did not exist at earlier stages (for example, before certain vaccination measures were introduced).

Therefore, these missing values are considered to be structurally missing. To preserve the integrity of the dataset and avoid introducing bias, they have been retained as they are.

This decision ensures that the dataset accurately reflects real-world conditions without artificially altering the underlying data.

### Duplicates

In [13]:
vaccines.duplicated().sum()

np.int64(0)

## Dtypes

In [14]:
vaccines.dtypes

Country                                object
Covid_Vaccine_Adm_Tot_A1D             float64
Covid_Vaccine_Adm_Tot_Boost           float64
Covid_Vaccine_Adm_Tot_Cps             float64
Covid_Vaccine_Adm_Tot_Doses           float64
Covid_Vaccine_Adm_Tot_Doses_Per100    float64
Covid_Vaccine_Cov_Tot_A1D             float64
Covid_Vaccine_Cov_Tot_Boost           float64
Covid_Vaccine_Cov_Tot_Cps             float64
Covid_Vaccine_Date_Intro_First         object
Covid_Vaccine_Date_Report_Tot_Last     object
Date                                   object
dtype: object

In [15]:
dates_col = ["Covid_Vaccine_Date_Intro_First", "Covid_Vaccine_Date_Report_Tot_Last", "Date"]
for i in dates_col:
    vaccines[i] = pd.to_datetime(vaccines[i])

In [16]:
vaccines.dtypes

Country                                       object
Covid_Vaccine_Adm_Tot_A1D                    float64
Covid_Vaccine_Adm_Tot_Boost                  float64
Covid_Vaccine_Adm_Tot_Cps                    float64
Covid_Vaccine_Adm_Tot_Doses                  float64
Covid_Vaccine_Adm_Tot_Doses_Per100           float64
Covid_Vaccine_Cov_Tot_A1D                    float64
Covid_Vaccine_Cov_Tot_Boost                  float64
Covid_Vaccine_Cov_Tot_Cps                    float64
Covid_Vaccine_Date_Intro_First        datetime64[ns]
Covid_Vaccine_Date_Report_Tot_Last    datetime64[ns]
Date                                  datetime64[ns]
dtype: object

In [17]:
vaccines["Date"].describe()

count                             7608
mean     2022-07-29 06:47:41.829652992
min                2021-01-31 00:00:00
25%                2021-10-31 00:00:00
50%                2022-07-31 00:00:00
75%                2023-04-30 00:00:00
max                2023-12-31 00:00:00
Name: Date, dtype: object

In [18]:
vaccines.columns

Index(['Country', 'Covid_Vaccine_Adm_Tot_A1D', 'Covid_Vaccine_Adm_Tot_Boost',
       'Covid_Vaccine_Adm_Tot_Cps', 'Covid_Vaccine_Adm_Tot_Doses',
       'Covid_Vaccine_Adm_Tot_Doses_Per100', 'Covid_Vaccine_Cov_Tot_A1D',
       'Covid_Vaccine_Cov_Tot_Boost', 'Covid_Vaccine_Cov_Tot_Cps',
       'Covid_Vaccine_Date_Intro_First', 'Covid_Vaccine_Date_Report_Tot_Last',
       'Date'],
      dtype='object')

## Dataset adjustment for merge
- Date
- Column names
- Granularity

### - Date

In [19]:
vaccines.dtypes

Country                                       object
Covid_Vaccine_Adm_Tot_A1D                    float64
Covid_Vaccine_Adm_Tot_Boost                  float64
Covid_Vaccine_Adm_Tot_Cps                    float64
Covid_Vaccine_Adm_Tot_Doses                  float64
Covid_Vaccine_Adm_Tot_Doses_Per100           float64
Covid_Vaccine_Cov_Tot_A1D                    float64
Covid_Vaccine_Cov_Tot_Boost                  float64
Covid_Vaccine_Cov_Tot_Cps                    float64
Covid_Vaccine_Date_Intro_First        datetime64[ns]
Covid_Vaccine_Date_Report_Tot_Last    datetime64[ns]
Date                                  datetime64[ns]
dtype: object

In [20]:
print(vaccines['Date'].min())
print(vaccines['Date'].max())

2021-01-31 00:00:00
2023-12-31 00:00:00

### - Column Names

In [21]:
vaccines.columns

Index(['Country', 'Covid_Vaccine_Adm_Tot_A1D', 'Covid_Vaccine_Adm_Tot_Boost',
       'Covid_Vaccine_Adm_Tot_Cps', 'Covid_Vaccine_Adm_Tot_Doses',
       'Covid_Vaccine_Adm_Tot_Doses_Per100', 'Covid_Vaccine_Cov_Tot_A1D',
       'Covid_Vaccine_Cov_Tot_Boost', 'Covid_Vaccine_Cov_Tot_Cps',
       'Covid_Vaccine_Date_Intro_First', 'Covid_Vaccine_Date_Report_Tot_Last',
       'Date'],
      dtype='object')

In this dataset, the `Country` column corresponds to the `Country_code` column in the ***COVID cases and deaths*** dataset.
The same happens with `Date` which is named as `Date_reported` in the other dataset. To ensure consistency and facilitate the merge process, the `Country` and `Date` columns will be renamed to `Country_code` and `Date_reported`.

In [22]:
vaccines.rename(columns={
    'Country': 'Country_code',
    'Date': 'Date_reported'}, inplace=True)

In [23]:
vaccines.columns

Index(['Country_code', 'Covid_Vaccine_Adm_Tot_A1D',
       'Covid_Vaccine_Adm_Tot_Boost', 'Covid_Vaccine_Adm_Tot_Cps',
       'Covid_Vaccine_Adm_Tot_Doses', 'Covid_Vaccine_Adm_Tot_Doses_Per100',
       'Covid_Vaccine_Cov_Tot_A1D', 'Covid_Vaccine_Cov_Tot_Boost',
       'Covid_Vaccine_Cov_Tot_Cps', 'Covid_Vaccine_Date_Intro_First',
       'Covid_Vaccine_Date_Report_Tot_Last', 'Date_reported'],
      dtype='object')

In [24]:
vaccines.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7608 entries, 3051 to 7554
Data columns (total 12 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Country_code                        7608 non-null   object
 1   Covid_Vaccine_Adm_Tot_A1D           7329 non-null   float64
 2   Covid_Vaccine_Adm_Tot_Boost         4830 non-null   float64
 3   Covid_Vaccine_Adm_Tot_Cps           7101 non-null   float64
 4   Covid_Vaccine_Adm_Tot_Doses         7426 non-null   float64
 5   Covid_Vaccine_Adm_Tot_Doses_Per100  7199 non-null   float64
 6   Covid_Vaccine_Cov_Tot_A1D           7112 non-null   float64
 7   Covid_Vaccine_Cov_Tot_Boost         4403 non-null   float64
 8   Covid_Vaccine_Cov_Tot_Cps           6803 non-null   float64
 9   Covid_Vaccine_Date_Intro_First      6807 non-null   datetime64[ns]
 10  Covid_Vaccine_Date_Report_Tot_Last  7375 non-null   datetime64[ns]
 11  Date_reported                       7608 non-null   datetime64[ns]
dtypes: datetime64[ns](3), float64(8), object(1)
memory usage: 772.7+ KB

In [27]:
vaccines.to_csv('../data/processed/vaccines_cleaned.csv', index=False)